### ISSUE TITLE
Publish Docker Images on new releases

### ISSUE THREAD

**Issue by JakeHartnell** [osmosis-labs/mesh-security-sdk#53]
@Anmol1696 is using them for testing in the Starship environment, and others may find them useful as well.

**Comment by Anmol1696** [comment]
I can take this up.

Tasks:
* CI to publish docker images to osmosis registry (might need credentials for this)
  * Optionally we can push this to `ghcr.io` as a package
* We might need a couple of docker images:
  * Scratch based docker image with Binary
  * Alpine based image with some more dependencies (used by Starship)

**Comment by alpe** [comment]
Thanks for adding this task. Happy if somebody moves this forward. 
IMHO the meshd app is only a demo app that will not run on production. Therefore focusing on the starship use-case makes sense
